### ISSUE TITLE
Websocket Error

### ISSUE THREAD

**Issue by benjamin852** [allanclempe/ether-wallet-flutter#6]
Hey! Awesome app! I am however getting an error which says  `Unhandled Exception: WebSocketChannelException: WebSocketChannelException:  WebSocketException: Connection to 'https://ropsten.infura.io:0/ws#' was not upgraded to websocket`. Is there a quick fix for this? Also where do I get the ERC20 token which this app supports?

**Comment by allanclempe** [comment]
Hi Ben, have you got the latest changes? I have updated the ws URL since [this commit](https://github.com/allanclempe/ether-wallet-flutter/commit/27307beab0ceed5c210eb01f8de7f8db8e6d213b#diff-861527c28c6fab7afabb0b69e0bbad4bR10). You should be using wss protocol instead of https.

Also, the ERC20 contract source code is available [here](https://github.com/allanclempe/ether-wallet-contract)

**Comment by benjamin852** [comment]
Got it thank you!
